on: [pull_request]
name: gotest
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [
            ubuntu-latest,
            macos-latest,
            windows-latest,
        ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Use Cache(on Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**\go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Use Cache
        if: runner.os != 'Windows'
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Download Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download
      - uses: nanasess/setup-chromedriver@master
      - name: Start chromedriver (Ubuntu, MacOS)
        if: runner.os != 'Windows'
        run: |
          export DISPLAY=:99
          chromedriver &
      - name: Start chromedriver (Windows)
        if: runner.os == 'Windows'
        run: chromedriver &
      # Run tests
      - name: Run tests
        run: make test
